name: Deploy React to GitHub Pages

permissions:
  contents: write
  
on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'  # You can specify your Node.js version here

    - name: more dependenciew
      run: 
        npm ci
      working-directory: ./password
  
    - name: List dependencies
      run: npm list -g --depth=0
      working-directory: ./password
  
    - name: Build
      run: |
        npm run build
      working-directory: ./password

    - name: ShowOutput
      run: ls -laR build
      working-directory: ./password

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5  # Check for the latest version
      with:
        branch: gh-pages  # Deployment branch
        folder: ./password/build  # Folder where your build is located
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub will automatically create this secret for you
